service: test-marge-pr-webhook
provider:
  name: aws
  runtime: ruby2.5
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: test-marge-pr-webhook/hello
          method: get
